"$schema" = 'https://starship.rs/config-schema.json'

# Gradient: Cyan -> Blue -> Aqua -> Purple -> Blue -> Cool Grey (bg3) -> Dark Grey (bg1)
format = """
[ÓÇ≤](color_cyan)\
$os\
$username\
$sudo\
[ÓÇ∞](bg:color_blue fg:color_cyan)\
$directory\
[ÓÇ∞](fg:color_blue bg:color_aqua)\
$git_branch\
$git_commit\
$git_status\
$git_metrics\
[ÓÇ∞](fg:color_aqua bg:color_purple)\
$aws\
$kubernetes\
[ÓÇ∞](fg:color_purple bg:color_blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$ruby\
$lua\
$zig\
[ÓÇ∞](fg:color_blue bg:color_bg3)\
$docker_context\
$conda\
$memory_usage\
$battery\
$cmd_duration\
[ÓÇ∞](fg:color_bg3 bg:color_bg1)\
$time\
[ÓÇ∞ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#2e3440'
color_bg3 = '#4c566a'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'
color_cyan = '#8ec07c'

# ------------------------------------------------------------------------------
# SYSTEM & IDENTITY
# ------------------------------------------------------------------------------

[os]
disabled = false
style = "bg:color_cyan fg:color_fg0"

[os.symbols]
Windows = "Û∞ç≤"
Ubuntu = "Û∞ïà"
SUSE = "Ôåî"
Raspbian = "Û∞êø"
Mint = "Û∞£≠"
Macos = "Û∞Äµ"
Manjaro = "Ôåí"
Linux = "Û∞åΩ"
Gentoo = "Û∞£®"
Fedora = "Û∞£õ"
Alpine = "ÔåÄ"
Amazon = "Ôâ∞"
Android = "Óúé"
Arch = "Û∞£á"
Artix = "Û∞£á"
EndeavourOS = "ÔÜó"
CentOS = "ÔåÑ"
Debian = "Û∞£ö"
Redhat = "Û±Ñõ"
RedHatEnterprise = "Û±Ñõ"
Pop = "Ôå™"
Kali = "Ôåß"

[username]
show_always = true
style_user = "bg:color_cyan fg:color_fg0"
style_root = "bg:color_cyan fg:color_fg0"
format = '[ $user ]($style)'

[sudo]
symbol = "ÔÇú "
style = "bg:color_cyan fg:color_fg0"
format = '[ $symbol]($style)'
disabled = false

# ------------------------------------------------------------------------------
# DIRECTORY
# ------------------------------------------------------------------------------

[directory]
style = "fg:color_fg0 bg:color_blue"
format = "[ $path ]($style)[$read_only]($style)"
truncation_length = 3
truncation_symbol = "‚Ä¶/"
read_only = " ÔÄ£"

[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = "ÔÄô "
"Music" = "Û∞ùö "
"Pictures" = "ÔÄæ "
"Developer" = "Û∞≤ã "

# ------------------------------------------------------------------------------
# GIT
# ------------------------------------------------------------------------------

[git_branch]
symbol = "Ôêò"
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[git_metrics]
added_style = "bold fg:color_fg0 bg:color_aqua"
deleted_style = "bold fg:color_red bg:color_aqua"
disabled = false
format = '[+$added]($added_style) [-$deleted]($deleted_style) '

# ------------------------------------------------------------------------------
# CLOUD & INFRASTRUCTURE
# ------------------------------------------------------------------------------

[aws]
symbol = "Ôâ∞ "
style = "bg:color_purple"
format = '[[ $symbol($profile )(\($region\) )](fg:color_fg0 bg:color_purple)]($style)'

[kubernetes]
symbol = "‚ò∏ "
style = "bg:color_purple"
format = '[[ $symbol$context ](fg:color_fg0 bg:color_purple)]($style)'

# ------------------------------------------------------------------------------
# LANGUAGES
# ------------------------------------------------------------------------------

[nodejs]
symbol = "Óúò"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = "Óòû "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = "Óû®"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = "Óòß"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = "Óòà"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = "Óâñ"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = "Óò¥"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = "Óòü"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = "ÓòÜ"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[ruby]
symbol = "Óûë"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[lua]
symbol = "Óò†"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[zig]
symbol = "ÔÉß"
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

# ------------------------------------------------------------------------------
# SYSTEM METRICS & UTILS
# ------------------------------------------------------------------------------

[docker_context]
symbol = "Ôåà"
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
symbol = "ÔÑå "
ignore_base = true
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[memory_usage]
symbol = "Û∞çõ "
disabled = false
threshold = 75
style = "bg:color_bg3"
format = '[[ $symbol${ram} ](fg:color_red bg:color_bg3)]($style)'

[battery]
disabled = false
full_symbol = "üîã "
charging_symbol = "‚ö°Ô∏è "
discharging_symbol = "üíÄ "
# We added the last line (threshold = 100) to force it to show always
display = [
  { threshold = 10, style = "bold red bg:color_bg3" },
  { threshold = 30, style = "bold yellow bg:color_bg3" },
  { threshold = 100, style = "bold green bg:color_bg3" }
]
format = '[[ $symbol$percentage ]($style)]($style)'

[cmd_duration]
min_time = 2000
style = "bg:color_bg3"
format = '[[ ‚è± $duration ](fg:color_yellow bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[ Ôê∫ $time ](fg:color_fg0 bg:color_bg1)]($style)'

# ------------------------------------------------------------------------------
# PROMPT
# ------------------------------------------------------------------------------

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ÓòÇ](bold fg:color_green)'
error_symbol = '[ÓòÇ](bold fg:color_red)'
vimcmd_symbol = '[Ôê¥](bold fg:color_green)'
vimcmd_replace_one_symbol = '[Ôê¥](bold fg:color_purple)'
vimcmd_replace_symbol = '[Ôê¥](bold fg:color_purple)'
vimcmd_visual_symbol = '[Ôê¥](bold fg:color_yellow)'